name: trunk

on:
  push:
    branches:
      - trunk

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Versions
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: PHP Syntax check
        working-directory: ./
        run: find . \( -name '*.php' \) -exec php -lf {} \;

      - name: Set up composer
        working-directory: ./
        run: composer install

      - name: PHPCS
        working-directory: ./
        run: composer run check-cs

      - name: Set up node modules
        working-directory: ./
        run: npm install

      - name: CSS Lint
        working-directory: ./
        run: npm run lint:css

      - name: JavaScript Lint
        working-directory: ./
        run: npm run lint:js

      - name: Test build
        working-directory: ./
        run: npm run build
